// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
 
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaM5ygQ8StkgwbnbKC3tqWCzfSAtgQwj8',
    appId: '1:586896011480:web:08ecda76f8da329e0a27ad',
    messagingSenderId: '586896011480',
    projectId: 'ilac-rehberi-3536b',
    authDomain: 'ilac-rehberi-3536b.firebaseapp.com',
    storageBucket: 'ilac-rehberi-3536b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-NNELMyticovcXOf2JwA0bGheeQIn498',
    appId: '1:586896011480:android:4033d560a4489ab80a27ad',
    messagingSenderId: '586896011480',
    projectId: 'ilac-rehberi-3536b',
    storageBucket: 'ilac-rehberi-3536b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqlhH0lrBCtiJb6vxL97bnmjU4YnXalSQ',
    appId: '1:586896011480:ios:b7164d7b95b2de610a27ad',
    messagingSenderId: '586896011480',
    projectId: 'ilac-rehberi-3536b',
    storageBucket: 'ilac-rehberi-3536b.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqlhH0lrBCtiJb6vxL97bnmjU4YnXalSQ',
    appId: '1:586896011480:ios:b7164d7b95b2de610a27ad',
    messagingSenderId: '586896011480',
    projectId: 'ilac-rehberi-3536b',
    storageBucket: 'ilac-rehberi-3536b.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaM5ygQ8StkgwbnbKC3tqWCzfSAtgQwj8',
    appId: '1:586896011480:web:54dc04c8c353b9a70a27ad',
    messagingSenderId: '586896011480',
    projectId: 'ilac-rehberi-3536b',
    authDomain: 'ilac-rehberi-3536b.firebaseapp.com',
    storageBucket: 'ilac-rehberi-3536b.firebasestorage.app',
  );
}
